---
name: Submit an idea
description: Tell us about a talk you'd like to see

body:
- type: markdown
  attributes:
    value: |
      Thank you for your interest in the Ansible community meetups !
      We are looking forward to your proposal on a wide range of Ansible topics whether you are a user, a contributor or a developer.

      If you have any questions, please feel free to reach out to us via:

      * Matrix: [#community:ansible.com](https://matrix.to/#/#community:ansible.im)
      * Libera.chat (IRC):` #ansible-community` on [libera.chat](https://web.libera.chat/#libera)

- type: textarea
  attributes:
    label: Talk idea/topic
    description: The description of your idea/topic
  validations:
    required: true
...
